"""
Feedback loop closers — pure functions that extract actionable signals
from existing analytics data and feed them back into the pipeline.

All functions are pure: take dicts in, return dicts out. No file I/O.
The analytics agent handles persistence.
"""

from __future__ import annotations

import json
from pathlib import Path


def aggregate_comment_intelligence(insights: dict) -> dict:
    """Aggregate comment analysis files into structured intelligence.

    Reads outputs/comment_analysis_*.json files (generated by comment_analyzer.py).
    Returns a dict suitable for insertion into channel_insights["comment_intelligence"].

    Args:
        insights: Current channel_insights dict (used for video context).

    Returns:
        {
            "trending_requests": [{"topic": str, "total_frequency": int, "total_likes": int}],
            "praise_themes": [str],
            "criticism_themes": [str],
            "sentiment_trajectory": {"positive_pct": float, "mixed_pct": float, "negative_pct": float},
            "videos_analyzed": int,
        }
    """
    comment_dir = Path("outputs")
    if not comment_dir.exists():
        return {"trending_requests": [], "praise_themes": [], "criticism_themes": [],
                "sentiment_trajectory": {}, "videos_analyzed": 0}

    # Collect all comment analysis files
    analyses = []
    for f in sorted(comment_dir.glob("comment_analysis_*.json"), reverse=True):
        try:
            data = json.loads(f.read_text())
            if data.get("status") == "complete" and data.get("comment_count", 0) > 0:
                analyses.append(data)
        except (json.JSONDecodeError, OSError):
            continue

    if not analyses:
        return {"trending_requests": [], "praise_themes": [], "criticism_themes": [],
                "sentiment_trajectory": {}, "videos_analyzed": 0}

    # Aggregate topic requests across all videos
    topic_agg: dict[str, dict] = {}
    for analysis in analyses:
        for req in analysis.get("topic_requests", []):
            topic = req.get("topic", "").strip().lower()
            if not topic:
                continue
            if topic not in topic_agg:
                topic_agg[topic] = {"topic": topic, "total_frequency": 0, "total_likes": 0}
            topic_agg[topic]["total_frequency"] += req.get("frequency", 0)
            topic_agg[topic]["total_likes"] += req.get("total_likes", 0)

    trending = sorted(topic_agg.values(), key=lambda x: x["total_likes"], reverse=True)[:15]

    # Aggregate praise and criticism themes
    praise_themes: list[str] = []
    criticism_themes: list[str] = []
    sentiment_counts = {"positive": 0, "mixed": 0, "negative": 0}

    for analysis in analyses:
        sentiment = analysis.get("sentiment", {})
        overall = sentiment.get("overall_sentiment", "mixed")
        if overall in sentiment_counts:
            sentiment_counts[overall] += 1

        for p in sentiment.get("praise", [])[:3]:
            if p not in praise_themes:
                praise_themes.append(p)
        for c in sentiment.get("criticisms", [])[:3]:
            if c not in criticism_themes:
                criticism_themes.append(c)

    total = sum(sentiment_counts.values()) or 1
    trajectory = {
        "positive_pct": round(sentiment_counts["positive"] / total * 100, 1),
        "mixed_pct": round(sentiment_counts["mixed"] / total * 100, 1),
        "negative_pct": round(sentiment_counts["negative"] / total * 100, 1),
    }

    return {
        "trending_requests": trending,
        "praise_themes": praise_themes[:10],
        "criticism_themes": criticism_themes[:10],
        "sentiment_trajectory": trajectory,
        "videos_analyzed": len(analyses),
    }


def extract_content_performance_signals(insights: dict) -> dict:
    """Extract which narrative structures correlate with high retention.

    Uses content_quality_correlation from channel_insights to identify
    what structural patterns the pipeline should favor.

    Args:
        insights: Current channel_insights dict.

    Returns:
        {
            "best_structure_types": [{"type": str, "avg_retention": float}],
            "best_hook_types": [{"type": str, "avg_retention": float}],
            "optimal_scene_count_range": str,
            "twist_impact": float | None,
            "hook_moment_impact": float | None,
            "script_quality_signals": [{"feature": str, "correlation": float}],
        }
    """
    cqc = insights.get("content_quality_correlation", {})
    features = cqc.get("feature_correlations", {})

    # Structure types ranked by retention
    structure_retention = features.get("structure_type_vs_retention", {})
    best_structures = sorted(
        [{"type": k, "avg_retention": v.get("avg_retention", 0)}
         for k, v in structure_retention.items()
         if isinstance(v, dict) and v.get("avg_retention")],
        key=lambda x: x["avg_retention"],
        reverse=True,
    )

    # Hook types ranked by retention
    hook_retention = features.get("hook_type_vs_retention", {})
    best_hooks = sorted(
        [{"type": k, "avg_retention": v.get("avg_retention", 0)}
         for k, v in hook_retention.items()
         if isinstance(v, dict) and v.get("avg_retention")],
        key=lambda x: x["avg_retention"],
        reverse=True,
    )

    # Optimal scene count
    scene_bands = features.get("scene_count_bands", {})
    best_band = None
    best_band_retention = 0
    for band_name, band_data in scene_bands.items():
        if isinstance(band_data, dict):
            ret = band_data.get("avg_retention", 0)
            if ret and ret > best_band_retention:
                best_band_retention = ret
                best_band = band_name

    # Twist and hook moment impact
    twist_data = features.get("has_twist_impact", {})
    twist_impact = None
    if isinstance(twist_data, dict) and "with" in twist_data and "without" in twist_data:
        w = twist_data["with"].get("avg_retention", 0) if isinstance(twist_data["with"], dict) else 0
        wo = twist_data["without"].get("avg_retention", 0) if isinstance(twist_data["without"], dict) else 0
        if w and wo:
            twist_impact = round(w - wo, 1)

    hook_data = features.get("has_hook_moment_impact", {})
    hook_impact = None
    if isinstance(hook_data, dict) and "with" in hook_data and "without" in hook_data:
        w = hook_data["with"].get("avg_retention", 0) if isinstance(hook_data["with"], dict) else 0
        wo = hook_data["without"].get("avg_retention", 0) if isinstance(hook_data["without"], dict) else 0
        if w and wo:
            hook_impact = round(w - wo, 1)

    # Script quality correlations
    sqc = features.get("script_quality_correlations", {})
    signals = sorted(
        [{"feature": k, "correlation": round(v, 3)}
         for k, v in sqc.items()
         if isinstance(v, (int, float)) and abs(v) > 0.1],
        key=lambda x: abs(x["correlation"]),
        reverse=True,
    )

    return {
        "best_structure_types": best_structures[:5],
        "best_hook_types": best_hooks[:5],
        "optimal_scene_count_range": best_band,
        "twist_impact": twist_impact,
        "hook_moment_impact": hook_impact,
        "script_quality_signals": signals[:10],
    }


def compute_era_retention_bands(insights: dict) -> dict:
    """Break retention_by_length_band down by era.

    Uses per_video_stats (which has content_classification with era) and
    retention_analysis to compute per-era, per-length-band retention.

    Args:
        insights: Current channel_insights dict.

    Returns:
        {
            "era_name": {
                "under_8min": {"avg_retention": float, "sample_count": int},
                "8_to_12min": {...},
                ...
            },
            ...
        }
    """
    per_video = insights.get("per_video_stats", [])
    if not per_video:
        return {}

    # Build era → length_band → retention list
    era_bands: dict[str, dict[str, list[float]]] = {}

    for video in per_video:
        classification = video.get("content_classification", {})
        era = classification.get("era", "unknown")
        retention = video.get("avg_retention_pct")
        duration_s = video.get("avg_view_duration_seconds", 0)

        if not retention or not duration_s:
            continue

        # Estimate total duration from retention + avg_view_duration
        # avg_view_duration = total_duration * (retention/100)
        if retention > 0:
            total_min = (duration_s / (retention / 100)) / 60
        else:
            continue

        # Bucket by length
        if total_min < 8:
            band = "under_8min"
        elif total_min < 12:
            band = "8_to_12min"
        elif total_min < 16:
            band = "12_to_16min"
        else:
            band = "over_16min"

        if era not in era_bands:
            era_bands[era] = {}
        if band not in era_bands[era]:
            era_bands[era][band] = []
        era_bands[era][band].append(retention)

    # Compute averages
    result: dict = {}
    for era, bands in era_bands.items():
        result[era] = {}
        for band, retentions in bands.items():
            result[era][band] = {
                "avg_retention": round(sum(retentions) / len(retentions), 1),
                "sample_count": len(retentions),
            }

    return result


def compute_audio_performance_signals(observations: list[dict]) -> dict:
    """Correlate voice/music params with YouTube retention.

    Uses param_observations (with attached metrics) to find which audio
    settings correlate with better performance.

    Args:
        observations: List of observation dicts from param_history.load_observations().

    Returns:
        {
            "param_correlations": [{"param": str, "correlation": float, "direction": str}],
            "best_performing_configs": [{"params_subset": dict, "avg_retention": float}],
            "sample_size": int,
        }
    """
    if not observations or len(observations) < 5:
        return {"param_correlations": [], "best_performing_configs": [], "sample_size": len(observations or [])}

    # Extract param-retention pairs
    audio_params = [
        "pause.reveal", "pause.breathing", "pause.default",
        "voice_speed.quote", "ducking.speech_volume", "ducking.silence_volume",
        "volume.act1", "volume.act2", "volume.act3", "volume.ending",
    ]

    param_values: dict[str, list[tuple[float, float]]] = {p: [] for p in audio_params}

    for obs in observations:
        metrics = obs.get("metrics", {})
        params = obs.get("params", {})
        retention = metrics.get("retention_pct") if metrics else None

        if not retention or not params:
            continue

        for param_key in audio_params:
            if param_key in params:
                param_values[param_key].append((params[param_key], retention))

    # Compute simple Spearman-like correlation for each param
    correlations = []
    for param_key, pairs in param_values.items():
        if len(pairs) < 5:
            continue

        # Rank-based correlation (simplified)
        n = len(pairs)
        param_vals = [p[0] for p in pairs]
        ret_vals = [p[1] for p in pairs]

        param_ranked = _rank(param_vals)
        ret_ranked = _rank(ret_vals)

        # Spearman rho
        d_sq_sum = sum((pr - rr) ** 2 for pr, rr in zip(param_ranked, ret_ranked))
        rho = 1 - (6 * d_sq_sum) / (n * (n * n - 1)) if n > 1 else 0

        if abs(rho) > 0.15:  # Only report meaningful correlations
            correlations.append({
                "param": param_key,
                "correlation": round(rho, 3),
                "direction": "higher_is_better" if rho > 0 else "lower_is_better",
                "sample_size": n,
            })

    correlations.sort(key=lambda x: abs(x["correlation"]), reverse=True)

    # Find best-performing configs (top quartile by retention)
    obs_with_metrics = [
        o for o in observations
        if (o.get("metrics") or {}).get("retention_pct") and o.get("params")
    ]
    obs_with_metrics.sort(key=lambda o: o["metrics"]["retention_pct"], reverse=True)

    top_quartile = obs_with_metrics[:max(1, len(obs_with_metrics) // 4)]
    best_configs = []
    for obs in top_quartile[:3]:
        params = obs.get("params", {})
        audio_subset = {k: v for k, v in params.items() if k in audio_params}
        best_configs.append({
            "params_subset": audio_subset,
            "avg_retention": obs["metrics"]["retention_pct"],
        })

    return {
        "param_correlations": correlations[:10],
        "best_performing_configs": best_configs,
        "sample_size": len(obs_with_metrics),
    }


def _rank(values: list[float]) -> list[float]:
    """Assign ranks to values (average rank for ties)."""
    indexed = sorted(enumerate(values), key=lambda x: x[1])
    ranks = [0.0] * len(values)

    i = 0
    while i < len(indexed):
        j = i
        while j < len(indexed) and indexed[j][1] == indexed[i][1]:
            j += 1
        avg_rank = (i + j + 1) / 2  # 1-based average
        for k in range(i, j):
            ranks[indexed[k][0]] = avg_rank
        i = j

    return ranks
