"""
War Room Layer 0 — Data Collector & Briefing Generator.

Pulls all available data from Supabase, local files, and YouTube Analytics
(when available) and packages it into a structured briefing document for
the 44-expert war room review.

Usage:
    python scripts/warroom_briefing.py                    # Generate briefing
    python scripts/warroom_briefing.py --output brief.json  # Save to file

Data sources:
    - Supabase: videos (long + shorts), analytics, topics queue, scene manifests
    - Local: lessons_learned.json, video-data.json, state files
    - YouTube Analytics: channel_insights.json (if available, generated by analytics agent)
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timezone

sys.path.append(str(Path(__file__).resolve().parent.parent))

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "outputs"


def _load_json(path: Path) -> dict | list | None:
    """Load a JSON file, return None on failure."""
    try:
        if path.exists():
            return json.loads(path.read_text())
    except Exception:
        pass
    return None


def _collect_supabase_data() -> dict:
    """Pull all video, analytics, and topic data from Supabase."""
    data = {
        "videos": {"long_form": [], "shorts": []},
        "analytics": [],
        "topics_queue": [],
        "scene_manifests": [],
        "param_observations": [],
    }

    try:
        from clients.supabase_client import get_client
        sb = get_client()
    except Exception as e:
        print(f"[Briefing] Supabase unavailable: {e}")
        return data

    # All videos
    try:
        vids = sb.table("videos").select(
            "id, topic, title, youtube_id, duration_seconds, word_count, "
            "created_at, scene_manifest, music_mood, music_source, music_adapted"
        ).order("created_at", desc=True).limit(50).execute()

        for v in vids.data or []:
            dur = v.get("duration_seconds") or 0
            entry = {
                "title": v.get("title", ""),
                "topic": v.get("topic", ""),
                "youtube_id": v.get("youtube_id", ""),
                "duration_seconds": dur,
                "duration_minutes": round(dur / 60, 1) if dur else 0,
                "word_count": v.get("word_count", 0),
                "created_at": v.get("created_at", ""),
                "music_mood": v.get("music_mood"),
                "music_source": v.get("music_source"),
                "music_adapted": v.get("music_adapted"),
                "has_scene_manifest": v.get("scene_manifest") is not None,
            }
            is_short = dur < 90
            if is_short:
                data["videos"]["shorts"].append(entry)
            else:
                data["videos"]["long_form"].append(entry)

            # Collect scene manifests
            if v.get("scene_manifest"):
                data["scene_manifests"].append({
                    "title": v.get("title", ""),
                    "youtube_id": v.get("youtube_id", ""),
                    "manifest": v["scene_manifest"],
                })

        print(f"[Briefing] Videos: {len(data['videos']['long_form'])} long-form, "
              f"{len(data['videos']['shorts'])} shorts")
    except Exception as e:
        print(f"[Briefing] Videos fetch failed: {e}")

    # Analytics per video
    try:
        anl = sb.table("analytics").select(
            "video_id, views, ctr_pct, avg_view_percentage, impressions, "
            "subscribers_gained, recorded_at"
        ).order("recorded_at", desc=True).limit(50).execute()
        data["analytics"] = anl.data or []
        total_views = sum(a.get("views", 0) for a in data["analytics"])
        print(f"[Briefing] Analytics: {len(data['analytics'])} rows, {total_views} total views")
    except Exception as e:
        print(f"[Briefing] Analytics fetch failed: {e}")

    # Topics queue
    try:
        topics = sb.table("topics").select(
            "topic, status, score, source, created_at, metadata"
        ).order("created_at", desc=True).limit(30).execute()
        data["topics_queue"] = topics.data or []
        queued = [t for t in data["topics_queue"] if t.get("status") == "queued"]
        print(f"[Briefing] Topics: {len(data['topics_queue'])} total, {len(queued)} queued")
    except Exception as e:
        print(f"[Briefing] Topics fetch failed: {e}")

    # Param observations (optimizer history)
    try:
        obs = sb.table("param_observations").select(
            "video_id, youtube_id, params, metrics, era, created_at"
        ).not_.is_("metrics", "null").order("created_at", desc=True).limit(20).execute()
        data["param_observations"] = obs.data or []
        print(f"[Briefing] Param observations: {len(data['param_observations'])}")
    except Exception as e:
        print(f"[Briefing] Param observations fetch failed: {e}")

    return data


def _collect_local_data() -> dict:
    """Collect data from local files."""
    data = {
        "lessons_learned": None,
        "latest_video_data": None,
        "latest_state": None,
        "channel_insights": None,
        "quality_report": None,
    }

    # lessons_learned.json
    lessons = _load_json(BASE_DIR / "lessons_learned.json")
    if lessons:
        # Summarize — don't include full raw data
        doctor = lessons.get("doctor_interventions", [])
        optimizer = lessons.get("optimizer_runs", [])
        data["lessons_learned"] = {
            "doctor_interventions_count": len(doctor),
            "recent_interventions": doctor[-5:] if doctor else [],
            "optimizer_runs_count": len(optimizer),
            "recent_grades": [
                {"topic": r.get("topic", ""), "grade": r.get("overall_grade", "?"),
                 "score": r.get("quality_score", 0)}
                for r in optimizer[-5:]
            ] if optimizer else [],
        }
        print(f"[Briefing] Lessons: {len(doctor)} interventions, {len(optimizer)} optimizer runs")

    # Latest video-data.json (the actual Remotion input)
    vd = _load_json(BASE_DIR / "remotion" / "src" / "video-data.json")
    if vd:
        scenes = vd.get("scenes", [])
        data["latest_video_data"] = {
            "total_duration_seconds": vd.get("total_duration_seconds", 0),
            "scene_count": len(scenes),
            "music_file": vd.get("music_file"),
            "music_adapted": vd.get("music_adapted", False),
            "has_stems": vd.get("music_stems") is not None,
            "scene_summary": [
                {
                    "scene_id": i + 1,
                    "mood": s.get("mood", ""),
                    "narrative_position": s.get("narrative_position", ""),
                    "narrative_function": s.get("narrative_function", ""),
                    "is_reveal_moment": s.get("is_reveal_moment", False),
                    "is_breathing_room": s.get("is_breathing_room", False),
                    "intent_silence_beat": s.get("intent_silence_beat", False),
                    "intent_scene_energy": s.get("intent_scene_energy"),
                    "intent_speech_intensity": s.get("intent_speech_intensity"),
                    "visual_treatment": s.get("visual_treatment", "standard"),
                    "claim_confidence": s.get("claim_confidence"),
                    "word_count": len((s.get("narration") or "").split()),
                    "duration_sec": round((s.get("end_time", 0) or 0) - (s.get("start_time", 0) or 0), 1),
                    "has_ai_image": bool(s.get("ai_image")),
                    "has_sfx": bool(s.get("sfx_file")),
                    "has_ambient": bool(s.get("ambient_file")),
                }
                for i, s in enumerate(scenes)
            ],
        }
        print(f"[Briefing] Latest video: {len(scenes)} scenes, "
              f"{vd.get('total_duration_seconds', 0) / 60:.1f} min")

    # Latest state file
    state_files = sorted(OUTPUT_DIR.glob("*_state.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    if state_files:
        state = _load_json(state_files[0])
        if state:
            data["latest_state"] = {
                "file": state_files[0].name,
                "topic": state.get("topic", ""),
                "pipeline_status": state.get("pipeline_status", ""),
                "elapsed_seconds": state.get("elapsed_seconds", 0),
                "completed_stages": state.get("completed_stages", []),
                "costs": state.get("costs", {}),
            }

    # channel_insights.json (generated by analytics agent on Railway)
    insights = _load_json(OUTPUT_DIR / "channel_insights.json")
    if not insights:
        insights = _load_json(BASE_DIR / "channel_insights.json")
    if insights:
        data["channel_insights"] = {
            "generated_at": insights.get("generated_at", ""),
            "has_retention_data": bool(insights.get("retention_curves")),
            "has_music_performance": bool(insights.get("music_performance")),
            "has_scene_correlation": bool(insights.get("scene_retention_correlation")),
            "era_performance": insights.get("era_performance", {}),
            "scene_retention_correlation": insights.get("scene_retention_correlation", {}),
            "music_performance": insights.get("music_performance", {}),
            "search_intelligence": insights.get("search_intelligence", {}),
        }
        print(f"[Briefing] Channel insights: generated {insights.get('generated_at', 'unknown')}")

    return data


def _compute_shorts_lift(supabase_data: dict) -> dict:
    """Compute shorts-to-long-form correlation from available data."""
    shorts = supabase_data["videos"]["shorts"]
    longs = supabase_data["videos"]["long_form"]
    # Match shorts to their parent long-form by topic similarity
    pairs = []
    for short in shorts:
        short_topic = short.get("topic", "").lower()
        for long_vid in longs:
            long_topic = long_vid.get("topic", "").lower()
            # Simple keyword overlap check
            short_words = set(short_topic.split())
            long_words = set(long_topic.split())
            overlap = len(short_words & long_words)
            if overlap >= 2:
                pairs.append({
                    "short_title": short.get("title", ""),
                    "long_title": long_vid.get("title", ""),
                    "short_youtube_id": short.get("youtube_id", ""),
                    "long_youtube_id": long_vid.get("youtube_id", ""),
                })
                break

    return {
        "total_shorts": len(shorts),
        "total_long_form": len(longs),
        "matched_pairs": len(pairs),
        "pairs": pairs[:10],
    }


def generate_briefing() -> dict:
    """Generate the complete Layer 0 briefing document."""
    print("[Briefing] Generating War Room Layer 0 briefing...")
    print("=" * 60)

    supabase_data = _collect_supabase_data()
    local_data = _collect_local_data()
    shorts_lift = _compute_shorts_lift(supabase_data)

    briefing = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "briefing_version": "2.0",

        # Channel overview
        "channel_overview": {
            "total_long_form": len(supabase_data["videos"]["long_form"]),
            "total_shorts": len(supabase_data["videos"]["shorts"]),
            "topics_queued": len([t for t in supabase_data["topics_queue"] if t.get("status") == "queued"]),
            "optimizer_observations": len(supabase_data["param_observations"]),
            "videos_with_scene_manifest": len(supabase_data["scene_manifests"]),
        },

        # All videos with analytics
        "videos": supabase_data["videos"],
        "analytics": supabase_data["analytics"],

        # Shorts-to-long-form correlation
        "shorts_lift": shorts_lift,

        # Latest video deep dive
        "latest_video": local_data["latest_video_data"],
        "latest_state": local_data["latest_state"],

        # Intelligence & learning
        "channel_insights": local_data["channel_insights"],
        "lessons_learned": local_data["lessons_learned"],
        "scene_manifests": supabase_data["scene_manifests"],
        "param_observations": supabase_data["param_observations"],

        # Topics pipeline
        "topics_queue": supabase_data["topics_queue"],

        # System state
        "system_info": {
            "tunable_params": 37,
            "optimizer_status": "active" if supabase_data["param_observations"] else "no data yet",
            "scene_manifest_status": "collecting" if supabase_data["scene_manifests"] else "no videos with new pipeline yet",
        },
    }

    print("=" * 60)
    print(f"[Briefing] Complete. {len(briefing['videos']['long_form'])} long-form, "
          f"{len(briefing['videos']['shorts'])} shorts, "
          f"{len(briefing['analytics'])} analytics rows")

    return briefing


def main():
    output_path = None
    if "--output" in sys.argv:
        idx = sys.argv.index("--output")
        if idx + 1 < len(sys.argv):
            output_path = Path(sys.argv[idx + 1])

    briefing = generate_briefing()

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(briefing, indent=2, default=str))
        print(f"\n[Briefing] Saved to {output_path}")
    else:
        # Print summary to stdout
        print(f"\n{'=' * 60}")
        print("WAR ROOM LAYER 0 BRIEFING SUMMARY")
        print(f"{'=' * 60}")
        overview = briefing["channel_overview"]
        print(f"  Long-form videos:  {overview['total_long_form']}")
        print(f"  Shorts:            {overview['total_shorts']}")
        print(f"  Topics queued:     {overview['topics_queued']}")
        print(f"  Optimizer data:    {overview['optimizer_observations']} observations")
        print(f"  Scene manifests:   {overview['videos_with_scene_manifest']} videos")

        latest = briefing.get("latest_video")
        if latest:
            print(f"\n  Latest video: {latest['scene_count']} scenes, "
                  f"{latest['total_duration_seconds'] / 60:.1f} min")
            moods = {}
            for s in latest.get("scene_summary", []):
                m = s.get("mood", "?")
                moods[m] = moods.get(m, 0) + 1
            print(f"  Mood distribution: {moods}")
            silence_beats = sum(1 for s in latest.get("scene_summary", []) if s.get("intent_silence_beat"))
            print(f"  Silence beats: {silence_beats}")

        insights = briefing.get("channel_insights")
        if insights:
            print(f"\n  Channel insights: {insights.get('generated_at', 'N/A')}")
            print(f"  Has retention data: {insights.get('has_retention_data', False)}")
            print(f"  Has scene correlation: {insights.get('has_scene_correlation', False)}")
            print(f"  Has music performance: {insights.get('has_music_performance', False)}")

        print("\nTo save full briefing: python scripts/warroom_briefing.py --output briefing.json")


if __name__ == "__main__":
    main()
